#index:
#    path: /
#    controller: App\Controller\DefaultController::index
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

fos_user_security_login:
  path:  /login/
  defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
  path:  /login_check
  defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
  path:  /logout
  defaults: { _controller: FOSUserBundle:Security:logout }